export const ADD_COUNTER = 'ADD_COUNTER'
export const REMOVE_COUNTER = 'REMOVE_COUNTER'
export const INTENSITY_TOGGLE_ON ='INTENSITY_TOGGLE_ON'
export const INTENSITY_TOGGLE_OFF ='INTENSITY_TOGGLE_OFF'
